Community Partner Logo - Technical Resources Community by Pooja Gera
pydelhi/conference pull request #162
Opened 2023-06-14 04:59 UTC by pooja-gera

- [x] Added the community partner logo to ``img/`` with the name ``technicalresourcescommunitybypoojagera.png``
- [x] Verified logo's correctness and looks for different screen sizes

2023-06-23 11:09 UTC, akshayaurora reviewed
Please remove .DS_Store

2023-06-23 11:10 UTC, Animesh-Ghosh requested changes

2023-06-23 11:10 UTC, Animesh-Ghosh commented on .DS_Store
Please remove the `.DS_Store` files

2023-06-23 11:10 UTC, Animesh-Ghosh commented on img/technicalresourcescommunitybypoojagera.png
Not sure if having a name of a person would be good.

2023-06-23 11:11 UTC, akshayaurora requested changes
Please remove your name from the community Logo.

2023-07-18 11:25 UTC, Animesh-Ghosh commented
Closing this for now. You may re-open it after making the requested changes.

2023-07-18 11:25 UTC, closed without merging